USE [master]
GO

/****** Object:  Database [bsuc]    Script Date: 11/14/2018 08:03:29 ******/
CREATE DATABASE [bsuc] ON  PRIMARY 
( NAME = N'bsuc', FILENAME = N'C:\Users\imhsc\Desktop\bsuc\bsuc\App_Data\bsuc.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'bsuc_log', FILENAME = N'C:\Users\imhsc\Desktop\bsuc\bsuc\App_Data\bsuc_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [bsuc] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bsuc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bsuc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bsuc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bsuc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bsuc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bsuc] SET ARITHABORT OFF 
GO

ALTER DATABASE [bsuc] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bsuc] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [bsuc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bsuc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bsuc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bsuc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bsuc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bsuc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bsuc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bsuc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bsuc] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bsuc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bsuc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bsuc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bsuc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bsuc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bsuc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bsuc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bsuc] SET  READ_WRITE 
GO

ALTER DATABASE [bsuc] SET RECOVERY FULL 
GO

ALTER DATABASE [bsuc] SET  MULTI_USER 
GO

ALTER DATABASE [bsuc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bsuc] SET DB_CHAINING OFF 
GO

